class_name FixedMath
extends RefCounted
## Integer math helpers for sim code. Results are exact integers, so they are
## identical on every platform.
##
## Angles are binary angles: ANGLE_FULL units per turn, so wrapping is a bit
## mask. Sines and cosines are fixed-point with TRIG_ONE as 1.0. Unit direction
## vectors (facings) have length DIR_ONE.

const ANGLE_FULL: int = 1024
const ANGLE_QUARTER: int = ANGLE_FULL / 4
const ANGLE_HALF: int = ANGLE_FULL / 2
const TRIG_ONE: int = 65536
const DIR_ONE: int = 1000
## 2 * pi * 1000, rounded: circumference = radius * TWO_PI_MILLI / 1000.
const TWO_PI_MILLI: int = 6283
## normalize() scales inputs up to at least this before taking the length.
const NORMALIZE_MIN_MAGNITUDE: int = 1 << 20

## sin(k * 2pi / ANGLE_FULL) * TRIG_ONE for k in 0..ANGLE_QUARTER, rounded.
## Generated by scripts/gen_sine_table.py so the sim never calls sin(): libm
## differs in the last bit between platforms.
const SIN_QUARTER: Array[int] = [
	0, 402, 804, 1206, 1608, 2010, 2412, 2814, 3216, 3617, 4019, 4420,
	4821, 5222, 5623, 6023, 6424, 6824, 7224, 7623, 8022, 8421, 8820, 9218,
	9616, 10014, 10411, 10808, 11204, 11600, 11996, 12391, 12785, 13180, 13573, 13966,
	14359, 14751, 15143, 15534, 15924, 16314, 16703, 17091, 17479, 17867, 18253, 18639,
	19024, 19409, 19792, 20175, 20557, 20939, 21320, 21699, 22078, 22457, 22834, 23210,
	23586, 23961, 24335, 24708, 25080, 25451, 25821, 26190, 26558, 26925, 27291, 27656,
	28020, 28383, 28745, 29106, 29466, 29824, 30182, 30538, 30893, 31248, 31600, 31952,
	32303, 32652, 33000, 33347, 33692, 34037, 34380, 34721, 35062, 35401, 35738, 36075,
	36410, 36744, 37076, 37407, 37736, 38064, 38391, 38716, 39040, 39362, 39683, 40002,
	40320, 40636, 40951, 41264, 41576, 41886, 42194, 42501, 42806, 43110, 43412, 43713,
	44011, 44308, 44604, 44898, 45190, 45480, 45769, 46056, 46341, 46624, 46906, 47186,
	47464, 47741, 48015, 48288, 48559, 48828, 49095, 49361, 49624, 49886, 50146, 50404,
	50660, 50914, 51166, 51417, 51665, 51911, 52156, 52398, 52639, 52878, 53114, 53349,
	53581, 53812, 54040, 54267, 54491, 54714, 54934, 55152, 55368, 55582, 55794, 56004,
	56212, 56418, 56621, 56823, 57022, 57219, 57414, 57607, 57798, 57986, 58172, 58356,
	58538, 58718, 58896, 59071, 59244, 59415, 59583, 59750, 59914, 60075, 60235, 60392,
	60547, 60700, 60851, 60999, 61145, 61288, 61429, 61568, 61705, 61839, 61971, 62101,
	62228, 62353, 62476, 62596, 62714, 62830, 62943, 63054, 63162, 63268, 63372, 63473,
	63572, 63668, 63763, 63854, 63944, 64031, 64115, 64197, 64277, 64354, 64429, 64501,
	64571, 64639, 64704, 64766, 64827, 64884, 64940, 64993, 65043, 65091, 65137, 65180,
	65220, 65259, 65294, 65328, 65358, 65387, 65413, 65436, 65457, 65476, 65492, 65505,
	65516, 65525, 65531, 65535, 65536,
]


## Floor of the square root of n, for 0 <= n < 2^62. Negative input returns 0.
static func isqrt(n: int) -> int:
	if n <= 0:
		return 0
	# The float root is only a starting guess. The loops correct it to the
	# exact floor, so the result never depends on float rounding.
	var r: int = int(sqrt(float(n)))  # purity-ok: a guess, corrected exactly below
	while r * r > n:
		r -= 1
	while (r + 1) * (r + 1) <= n:
		r += 1
	return r


## a / b rounded toward negative infinity, for b > 0. GDScript's / truncates
## toward zero, which rounds negative values the wrong way.
static func div_floor(a: int, b: int) -> int:
	var q: int = a / b
	if a % b != 0 and a < 0:
		q -= 1
	return q


## a / b rounded to the nearest integer, halves away from zero, for b > 0.
## Symmetric: div_round(-a, b) == -div_round(a, b).
static func div_round(a: int, b: int) -> int:
	if a < 0:
		return -((-a + b / 2) / b)
	return (a + b / 2) / b


## sin of a binary angle, times TRIG_ONE. Any angle wraps, negatives included.
static func sin_b(angle: int) -> int:
	var a: int = angle & (ANGLE_FULL - 1)
	if a < ANGLE_QUARTER:
		return SIN_QUARTER[a]
	if a < ANGLE_HALF:
		return SIN_QUARTER[ANGLE_HALF - a]
	if a < ANGLE_HALF + ANGLE_QUARTER:
		return -SIN_QUARTER[a - ANGLE_HALF]
	return -SIN_QUARTER[ANGLE_FULL - a]


## cos of a binary angle, times TRIG_ONE.
static func cos_b(angle: int) -> int:
	return sin_b(angle + ANGLE_QUARTER)


## Euclidean length of (x, z), floored.
static func length(x: int, z: int) -> int:
	return isqrt(x * x + z * z)


## (x, z) scaled to the given length, each component rounded. The zero vector
## stays zero. Components must be below 2^30 in magnitude.
static func normalize(x: int, z: int, new_length: int) -> Vector2i:
	if x == 0 and z == 0:
		return Vector2i.ZERO
	# isqrt floors, which is a large relative error for short vectors (|(3, 7)|
	# would be 7, not 7.6). Scale the larger component up to at least 2^20
	# first; direction is unchanged and the floor error becomes negligible.
	var sx: int = x
	var sz: int = z
	var big: int = maxi(absi(x), absi(z))
	while big < NORMALIZE_MIN_MAGNITUDE:
		sx *= 2
		sz *= 2
		big *= 2
	var magnitude: int = length(sx, sz)
	return Vector2i(div_round(sx * new_length, magnitude), div_round(sz * new_length, magnitude))


## World (x, z) offset of a local (right, forward) offset for a unit facing
## (facing_x, facing_z), a direction of length DIR_ONE. Right is
## (-facing_z, facing_x): facing -z (north), right is +x (east).
static func rotate_local(right: int, forward: int, facing_x: int, facing_z: int) -> Vector2i:
	return Vector2i(
		div_round(-right * facing_z + forward * facing_x, DIR_ONE),
		div_round(right * facing_x + forward * facing_z, DIR_ONE)
	)
